#!/bin/bash

# Create DB and user
mysql -e "create database zabbix character set utf8 collate utf8_bin;"
mysql -e "grant all privileges on zabbix.* to zabbix@localhost identified by '$(cat /var/lib/nethserver/secrets/zabbix)';"

# Set zabbix shell to bash for login as zabbix user to write db
usermod -s /bin/bash zabbix

# Fill DB
/usr/bin/mysql zabbix < /usr/share/zabbix-mysql/schema.sql
/usr/bin/mysql zabbix < /usr/share/zabbix-mysql/images.sql
/usr/bin/mysql zabbix < /usr/share/zabbix-mysql/data.sql

# Set zabbix shell to /bin/false again for security
usermod -s /bin/false zabbix

# import map images of Andy Wismer
#mv /root/zabbiximages /var/lib/pgsql/data/
#cd /var/lib/pgsql/data/zabbiximages
#for d in *.png; do su postgres -c "psql zabbix postgres -c \"insert into images (imageid,imagetype,name,image) values ((select max(imageid) +1 from images),1,'$d',pg_read_binary_file('zabbiximages/$d'));\""; done

# rename backup monitoring script
mv /usr/local/bin/nethbackup_check /usr/local/bin/nethbackup_check.py
